# Generated by Django 6.0.4 on 2026-05-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0002_department_manager'),
        ('identity', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'department', 'is_active'], name='user_role_dept_active_idx'),
        ),
    ]
