# Generated by Django 6.0.4 on 2026-04-12 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Rapor Başlığı')),
                ('report_type', models.CharField(choices=[('DEPARTMENT_PERFORMANCE', 'Departman Performansı'), ('PERSONNEL_WORKLOAD', 'Personel İş Yükü'), ('TICKET_SUMMARY', 'Bilet Özeti'), ('CATEGORY_ANALYSIS', 'Kategori Analizi')], max_length=30, verbose_name='Rapor Türü')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('summary_data', models.JSONField(blank=True, default=dict, verbose_name='Özet Veriler')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Rapor Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='departments.department', verbose_name='Departman')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
