# Generated by Django 6.0.4 on 2026-04-10 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Konu')),
                ('message', models.TextField(max_length=1000, verbose_name='Mesaj')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/%Y/%m/', verbose_name='Dosya Eki')),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('IN_PROGRESS', 'İşlemde'), ('CLOSED', 'Kapalı')], default='OPEN', max_length=20, verbose_name='Durum')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='Çözüm Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapatılma Tarihi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Üstlenen Personel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.category', verbose_name='Kategori')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.department', verbose_name='Departman')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Talep Sahibi')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Biletler',
                'ordering': ['-created_at'],
            },
        ),
    ]
