# Generated by Django 6.0.4 on 2026-04-12 21:30

import django.db.models.deletion
import tickets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/%Y/%m/', validators=[tickets.validators.validate_file_extension, tickets.validators.validate_file_size, tickets.validators.validate_file_content], verbose_name='Dosya Eki'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.department', verbose_name='Departman'),
        ),
    ]
