# Generated by Django 6.0.4 on 2026-04-13 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_attachment_alter_ticket_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Düşük'), ('NORMAL', 'Normal'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='NORMAL', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_actions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='Bilet')),
            ],
            options={
                'verbose_name': 'Bilet Geçmişi',
                'verbose_name_plural': 'Bilet Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
