# Generated by Django 6.0.4 on 2026-05-01 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager'),
        ('tickets', '0004_ticketcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='ticket_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sender'], name='ticket_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='ticket_assigned_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'closed_at'], name='ticket_status_closedat_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['actor'], name='tickethist_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['ticket', '-created_at'], name='tickethist_ticket_created_idx'),
        ),
    ]
